theme: jekyll-swiss
# Site Settings
locale                   : "ja-JP"  # 日本語を扱うなら変更しておく
title                    : "On my way to Victoria"
name                     : "PeterGrainfield"
description              : "There is nothing"
repository               : "PeterGrainfield/PeterGrainfield.github.io"  # GitHub 上のリポジトリを指定する